config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  # Routes the pages to the home page 

  resources :pages
  # Resources maps all of the conventional routes for a collection of resources, such as "pages"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create 
    @page = Page.new(page_params)


    if @page.save
      redirect_to @page
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @page = Page.find(params[:id])
  end
    
  def update
    @page = Page.find(params[:id])

    if @page.update(page_params)
      redirect_to @page
    else
      render :edit, status: :unprocessable_entity
  end
end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def page_params
      params.require(:page).permit(:name, :brand, :size, :status, :condition, :box, :image, :price1, :price2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Corinthia&family=Klee+One:wght@600&family=Monsieur+La+Doulaise&family=Petit+Formal+Script&family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet">
    <title>SHOE THERAPY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class= 'background_image'>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with model: @page do |form| %>
    
    <br>

    <div>
      <%= form.label :name, "NAME OF YOUR SHOE:" %><br>
      <%= form.text_field :name %>
      <% page.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <br>

    <div>
      <%= form.label :brand, "BRAND:" %><br>
      <%= form.text_field :brand %><br>
      <% page.errors.full_messages_for(:brand).each do |message| %>
        <div><%= message %></div> 
      <% end %>
    </div>

    <br>

    <div>
      <%= form.label :size, "SIZE:" %><br>
      <%= form.text_field :size %>
      <% page.errors.full_messages_for(:size).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <br>

    <div>
      <%= form.label :status, "STATUS:" %><br>
      <%= form.select :status, [['Available'], ['Sold - Not Yet Shipped'], ['Sold - Shipped']] %><br>
      <% page.errors.full_messages_for(:status).each do |message| %>
        <div><%= message %></div> 
      <% end %>
    </div>

    <br>

    <div>
      <%= form.label :condition, "CONDITION:" %><br>
      <%= form.select :condition, [['New - Never Worn'], ['Excellent Used Condition'], ['Good Used Condition'], ['Very Used Condition']] %><br>
      <% page.errors.full_messages_for(:condition).each do |message| %>
        <div><%= message %></div> 
      <% end %>
    </div>

    <br>

    <div>
      <%= form.label :box, "ORIGINAL BOX:" %><br>
      <%= form.select :box, [['Yes'], ['No']] %><br>
      <% page.errors.full_messages_for(:box).each do |message| %>
        <div><%= message %></div> 
      <% end %>
    </div>

    <br>
    
    <div>
      <%= form.label "UPLOAD PHOTO" %>
      <%= form.file_field :image %><br>
    </div>

    <br>

    <div>
      <%= form.label :price1, "PURCHASE PRICE:" %><br>
      <%= form.text_field :price1 %><br>
      <% page.errors.full_messages_for(:price1).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <br>  

    <div>
      <%= form.label :price2, "SOLD FOR:" %><br>
      <%= form.text_field :price2 %><br>
      <% page.errors.full_messages_for(:price2).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <br>  
    <br>

    <nav>
      <%= form.submit "SUBMIT" %>
    </nav>
  <% end %>
  

app/views/pages/edit.html.erb
<h1>SHOE THERAPY</h1>

<nav>
<%= button_to link_to "BACK TO PREVIOUS PAGE", :back %>
<%= button_to link_to "HOME PAGE", :root %>
</nav>

<h2>EDIT SHOE</h2>

<article id= 'form'> 
<%= render "form", page: @page %>
</article>

app/views/pages/index.html.erb
<h1>SHOE THERAPY</h1>

<nav>
  <a><%= button_to link_to "ADD A NEW SHOE", new_page_path %></a>
</nav>
<br>
<section>
  <% @pages.each do |page| %>
    <article>
      <a><%= link_to page.name.upcase, page %></a>
      <br>
      <p> BRAND: <%= page.brand %></p>
      <p> SIZE: <%= page.size %></p>
      <p> STATUS: <%= page.status %></p>
      <p> CONDITION: <%= page.condition %></p>
      <p> ORIGINAL BOX: <%= page.box %></p>
      <%= image_tag page.image, :style => "max-height:300px" %>
      <p> PURCHASE PRICE: <%= page.price1 %></p>
      <p> SOLD FOR: <%= page.price2 %></p>
    </article>
  <% end %>
</section>

app/views/pages/new.html.erb
<h1>SHOE THERAPY</h1>

<nav>
<%= button_to link_to "BACK TO PREVIOUS PAGE", :back %>
<%= button_to link_to "HOME PAGE", :root %>
</nav>

<h2>ADD A NEW SHOE</h2>

<article id= 'form'> 
    <%= render "form", page: @page %>
</article>

app/views/pages/show.html.erb
<h1>SHOE THERAPY</h1>

<nav>
<%= button_to link_to "BACK TO PREVIOUS PAGE", :back %>
<%= button_to link_to "HOME PAGE", :root %>
<nav>

<br>

<article>
    <p> BRAND: <%= @page.brand %></p>
    <p> SIZE: <%= @page.size %></p>
    <p> STATUS: <%= @page.status %></p>
    <p> CONDITION: <%= @page.condition %></p>
    <p> ORIGINAL BOX: <%= @page.box %></p>
    <p><%= image_tag @page.image, :style => "max-height:300px" %></p>
    <p> PURCHASE PRICE: <%= @page.price1 %></p>
    <p> SOLD FOR: <%= @page.price2 %></p>
</article>

<br>

<nav>
    <a><%= button_to link_to "EDIT", edit_page_path(@page) %></a>
    <a><%= button_to link_to "DELETE", page_path(@page), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                        } %></a>
</nav>